
format = """
[┌─](bold green) $username@$hostname $directory
[│](bold green)
[└─>](bold green) """

[username]
format = "[$user]($style)"
style_user = "bold dimmed blue"
show_always = true

[hostname]
ssh_only = false

